idf_component_register(SRCS "src/app/ubac_main.c"
                       "src/app/ntc_history.c"
                       "src/drivers/i2c_manager.c"
                       "src/drivers/mux.c"
                       "src/drivers/ads1115.c"
                       "src/drivers/ntc_sensor.c"
                       "src/drivers/fan_ctrl.c"
                       "src/net/web_server.c"
                       "src/net/wifi_app.c"
                       "src/net/dns_server.c"
                       "src/net/udp_responder.c"
                       INCLUDE_DIRS "include"
                       EMBED_TXTFILES "html/config.html" "html/dashboard.html")
