idf_component_register(SRCS "src/ubac_main.c"
                       "src/i2c_manager.c"
                       "src/mux.c"
                       "src/ads1115.c"
                       "src/ntc_sensor.c"
                       "src/fan_ctrl.c"
                       "src/web_server.c"
                       "src/wifi_app.c"
                       "src/dns_server.c"
                       "src/udp_responder.c"
                       "src/ntc_history.c"
                       INCLUDE_DIRS "include"
                       EMBED_TXTFILES "html/config.html" "html/dashboard.html")
